site_name: Webmail-User-Documentation
site_url: https://mydomain.org/Webmail-User-Documentation

nav:
  - Home: index.md
  - Setting up external email client: Setting up external email client.md
  - Setting up identity: Setting up identity.md
  - Setting up filters: Setting up filters.md
  - Signing up for student benefits: Signing up for student benefits.md
  - Troubleshooting: Troubleshooting.md
  - Glossary: Glossary.md

theme:
  name: material
  palette:
    scheme: header1
    primary: indigo

  logo: assets/channels4_profile.jpg
  favicon: assets/channels4_profile.jpg

# MARKDOWN EXTENSIONS
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - pymdownx.tasklist
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheet/extra.css
