site_name: Webmail-User-Documentation
site_url: https://mydomain.org/Webmail-User-Documentation
theme:
  name: material
  logo: assets/channels4_profile.jpg
  favicon: assets/channels4_profile.jpg

# MARKDOWN EXTENSIONS
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
